version: '2'

services:
  database:
    container_name: witness-db
    image: mysql:8
    restart: always
    volumes:
      - $IOTEX_WITNESS/data/mysql:/var/lib/mysql:rw
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  iotex-witness:
    container_name: witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-iotex.yaml:/etc/iotube-witness/witness-config-iotex.yaml:ro
    links:
      - database
    command: witness -config=/etc/iotube-witness/witness-config-iotex.yaml
  ethereum-witness:
    container_name: witness
    image: witness:latest
    restart: on-failure
    volumes:
      - $IOTEX_WITNESS/etc/witness-config-ethereum.yaml:/etc/iotube-witness/witness-config-ethereum.yaml:ro
    links:
      - database
    command: witness -config=/etc/iotube-witness/witness-config-ethereum.yaml
  cron:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - $IOTEX_WITNESS/etc/crontab:/var/spool/cron/crontabs/root
      - $IOTEX_WITNESS/etc/backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: witness

  backup:
    image: busybox
    volumes:
      - $IOTEX_WITNESS/data/backup:/backup
