chain: "bsc"
interval: 1m
clientURL: "https://bsc-dataseed.binance.org/"
ethConfirmBlockNumber: 2
ethGasPriceLimit: 10
port: 7003
privateKey: ""
slackWebHook: "" 
validatorAddress: "0x116404F86e97846110EA08cd52fC2882d4AD3123"
databaseURL: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
transferTableName: "bsc_transfers"
witnessTableName: "bsc_witnesses"
