chain: "heco"
interval: 1m
clientURL: "https://http-mainnet-node.huobichain.com"
ethConfirmBlockNumber: 2
ethGasPriceLimit: 10
port: 7002
privateKey: ""
slackWebHook: "" 
validatorAddress: "0xDe9395d2f4940aA501f9a27B98592589D14Bb0f7"
databaseURL: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
transferTableName: "heco_transfers"
witnessTableName: "heco_witnesses"
