chain: "ethereum"
interval: 5m
clientURL: ""
ethConfirmBlockNumber: 20
ethGasPriceLimit: 10000000000
port: 7000
privateKey: ""
slackWebHook: "" 
validatorAddress: "0xd8165188CCC135B3A3B2a5D2Bc3AF9D94753d955"
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
  driver: "mysql"
transferTableName: "ethereum_transfers"
witnessTableName: "ethereum_witnesses"
