refreshInterval: 60m
ethConfirmBlockNumber: 2
ethGasPriceLimit: 20000000000
slackWebHook: ""
httpPort: 8080
db:
  url: "root:kdfjjrU64fjK58H@tcp(database:3306)/?parseTime=true"
  driverName: "mysql"
iotex:
  client: "api.iotex.one:443"
  tokenListContract: "io12fpehpj76ydgjyuzrlcgeys5w3s45p86p4h695"
  witnessListContract: "io1m69g89xkfduplvkzh67vxenmeswqz3kdywjaew"
  cashierContract: "io10jn0kf7te225hv7uzfc7sza5hwlgqhmljdyudj"
  validatorContract: "io1k0ncs42tj67cyt0lysgkzfges2ktj9vslkstjh"
  privateKey: ""
  dbTableName: "tube.erc2xrc"
  pullInterval: 1m
  pullBatchSize: 100
  processInterval: 1m
  processBatchSize: 1
  retryDuration: 60s
ethereum:
  client: ""
  tokenListContract: "0x7c0bef36e1b1cbeb1f1a5541300786a7b608aede"
  witnessListContract: "0x8598dF1Ec0ac7dfBa802f4bDD93A6B93bd0AD83f"
  cashierContract: "0x62ee799b09c2b12f3350a73a54d07434023ebcca"
  validatorContract: "0xf70BDF9D3eEdD1b243A03B45d1EFC7B5e3f701ab"
  privateKey: ""
  dbTableName: "tube.xrc2erc"
  pullInterval: 1m
  pullBatchSize: 100
  processInterval: 1m
  processBatchSize: 1
  retryDuration: 30m
