ethGasPriceLimit: "20000000000"
slackWebHook: ""
httpPort: 8080
db:
  url: ""
  driverName: "mysql"
iotex:
  client: "api.testnet.iotex.one:443"
  threshold: "20000000000000000000000"
  tokenListContract: ""
  voterListContract: ""
  cashierContract: ""
  validatorContract: ""
  privateKey: ""
  dbTableName: "erc2xrc"
  pullInterval: 1m
  voteInterval: 1m
  checkInterval: 10m
ethereum:
  client: "https://ropsten.infura.io/v3/"
  threshold: "20000000000000000000000"
  tokenListContract: ""
  voterListContract: ""
  cashierContract: ""
  validatorContract: ""
  privateKey: ""
  dbTableName: "erc2xrc"
  pullInterval: 1m
  voteInterval: 1m
  checkInterval: 10m
