chain: "iotex"
clientURL: "api.iotex.one:443"
relayerURL: ":7000"
privateKey: ""
slackWebHook: ""
validatorContractAddress: "0x"
cashierContractAddress: "io"
startBlockHeight: 0
batchSize: 1000
processInterval: 1m
databaseURL: "root:kdfjjrU64fjK58H@tcp(database:3306)/witness?parseTime=true"
transferTableName: "iotex_transfers"
tokenPairTableName: "iotex_to_ethereum_pairs"
